// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWO5cF_2JZ3NivtmdfLlNI1p_8e2LCAXs',
    appId: '1:146589325592:web:d999c094b14776410f266d',
    messagingSenderId: '146589325592',
    projectId: 'book-reader-7ae88',
    authDomain: 'book-reader-7ae88.firebaseapp.com',
    databaseURL: 'https://book-reader-7ae88-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'book-reader-7ae88.appspot.com',
    measurementId: 'G-SKQN8PQ4XP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoD7z-pyIAxpa_cxCtMc8ZmtlQYVFzULE',
    appId: '1:146589325592:android:ab2f992775aabd8a0f266d',
    messagingSenderId: '146589325592',
    projectId: 'book-reader-7ae88',
    databaseURL: 'https://book-reader-7ae88-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'book-reader-7ae88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWiA0jemF6EklJTMIHtO6hKWDYDQ2dF-4',
    appId: '1:146589325592:ios:5a23ee44b1020acb0f266d',
    messagingSenderId: '146589325592',
    projectId: 'book-reader-7ae88',
    databaseURL: 'https://book-reader-7ae88-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'book-reader-7ae88.appspot.com',
    iosClientId: '146589325592-re4qm07h7o87ojipg1tbfrc1ihf8si03.apps.googleusercontent.com',
    iosBundleId: 'com.indesigngraphics.bookReader',
  );
}
